name: scratcher
description: Scratch card widget which temporarily hides content from the user.
homepage: https://github.com/vintage/scratcher

version: 2.4.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint:
  flutter_test:
    sdk: flutter
