name: scratcher
description: Scratch card widget which temporarily hides content from the user.
homepage: https://github.com/vintage/scratcher

version: 2.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint:
  flutter_test:
    sdk: flutter
